### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by Unitorami** [DerekPascarella/NeonGenesisEvangelionTypingProjectAdvanced-EnglishPatchDreamcast#1]
Hi. I was wondering if you knew how to help me. I am running Flycast and tried to load the patched version. It brings me to the bios and tells me to load the game. I'm not sure how to get past the screen. It worked prior to patching so maybe I need to adjust a setting somewhere? Thank you!

**Comment by DerekPascarella** [comment]
Try turning the HLE BIOS setting on.  For example, with RetroArch+Flycast:

![image](https://user-images.githubusercontent.com/28241702/150198704-67e1c3a5-6eef-42d6-912c-607bd80efc6b.png)

**Comment by Unitorami** [comment]
Thank you so much. That fixed the issue. I'd like to mention that I have developed a set for your first patch in Retroachievements and will be developing a set for this one as well. We are having a Dreamcast support launch soon and these two games will be added to the launch list. Thank you for your contributions!

**Comment by DerekPascarella** [comment]
Very cool!
